### ISSUE TITLE
'autoplay':true not working in javascript version

### ISSUE THREAD

**Issue by fdelapena** [fbricker/muses#13]
This option is working fine with the flash version but not with the HTML5 version.

Tested with hosted version.

**Comment by fbricker** [comment]
Hi, autoplay is disabled on HTML5 version of the player, since for now, HTML5 version is intended to be used on mobile devices (which in most cases -like iPhone and many version of android-) does not allows auto-play.

I think iPhone and most versions of android disables the autoplay option to protect the user internet connection. That's why any audio that you want to play there has to start from a user event.

Anyway... I understand that HTML5 version is also used on desktop (if the browser does not haves flash plugin installed), but so far as html5 is in beta stage, it just has autoplay disabled :(

Thanks!

**Comment by fdelapena** [comment]
Hi, thanks @fbricker, you're right with autoplay on mobile browsers. Because this is user-agent specific, having it enabled to have support for desktop browser users some day would be nice. Some users don't install Flash on desktop for security reasons or operating system restrictions or support. 

Nowadays Flash Player is not heavily required anywhere so it's more usual than before having it uninstalled, specially on GNU/Linux, that's the reason about this petition, as I guess mobile browsers will do graceful degradation. I think documenting this on parameter configuration when using the HTML5 version would prevent questions about this device fact.

**Comment by fbricker** [comment]
Yes... the idea is to enable this feature on desktop HTML5 player in the near future :)

Also, once the HTML5 version goes out of beta stage, it'll soon become the default option using flash version only if the browser does not support some specific codec that the flash version does.

Thanks!
Federico
