### ISSUE TITLE
html5 player?

### ISSUE THREAD

**Issue by pablote** [fbricker/muses#18]
the web page mentions support for html5 player but I haven't found a way to use it, do you have samples or indication on how to use it? thanks

**Comment by fbricker** [comment]
Hi, HTML5 feature appears automatically when your browser doesn't have the flash plugin enbled.
Few considerations:

- So far it only works with the hosted-by-muses version of the code.


- If you want to force the HTML5 version of the player, you must add the **'forceHTML5':true** option to the generated code, like this:
```javascript
MRP.insert({
'url':'http://192.241.214.243:9020/;',
'codec':'mp3',
'volume':65,
'autoplay':true,
'buffering':5,
'forceHTML5':true, // <-- Add this line
'title':'Radio Vermont',
'welcome':'WELCOME TO...',
'bgcolor':'#FFFFFF',
'skin':'uuskin',
'width':166,
'height':83
});
```

**Comment by sasha2002** [comment]
Still can't see any NEW version where i can set this.
Can you provide link?
I want hosted.
On site you can't change version of player :
Player Version: 	Flash

**Comment by fbricker** [comment]
Hi, so far the HTML5 version is still in beta stage (pre-release actually). We don't want to give the "hoste it yourself" version of the HTML5 player until we reach a good stability and compatibility.

We allow the HTML5 version on the "Hosted-by-muses" mode, since we know we can update it automatically if we find some bug.

Please wait some more time if you require the HTML5 version of player to be hosted on your servers (or you can use the hoster-by-muses version meanwhile).
