### ISSUE TITLE
No pause functionality

### ISSUE THREAD

**Issue by ashrafsabrym** [fbricker/muses#20]
Hello,

Thanks for this good product.

One of the broadcasts I listen to uses Muses. That's how I knew about it.
I noticed though that the player doesn't have the pause functionality (the website uses the HTML5 version).
While certainly the HTML Audio element has a [pause](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/pause) method, I see that the JS code generated for Muses pauses and resets the element instance (in the stopAudio method):
`stopAudio = (function (a){this.desiredStatus="stop";null!=this.audio&&(this.audio.pause(),this.audio.src="");a&&(this.lastAudioStatus=4,this.metadataLoader.stop())})`

Haxe is not my profession, but I see that the MP3Player class uses `flash.media.Sound` which doesn't have a pause method.

Why the need to pause? Sometimes one wants to leave for a reason or another, and I want to pause then continue from where I left. The HTML Audio element (at least on Firefox where I listen) continue buffering streamed audio when paused.

**Comment by fbricker** [comment]
Hi, I understand the benefits of a Pause feature.

But the problem with Pause feature is that most people gets confused with pause/stop when you're listening live radio stations. So, if we provide the pause feature, many people will pause the streamings instead of stopping them, which is a problem since many radio station will have listeners consuming bandwidth in vane... Also, some browsers will just hang after certain amount of time with the streaming paused (due to the size of the audio file being cached).

Maybe something can be done in the javascript API (like providing the pause feature from javascript so each station owner can decide if they want that or not). But this will raise conflicts with other features like automatic reconnect, buffering management/release and metadata display among others... This is why pause is not implemented yet :/

Anyway, I'm not saying Muses will never have pause feature, but right now is not in the priority list.

Thanks for using Muses 👍

**Comment by ashrafsabrym** [comment]
I'm using this feature on Firefox on desktop. It doesn't hang nor cache infinitely. It has some threshold but I can't determine it accurately (maybe 40 or 50 minutes). If I leave it for a couple of hours, it doesn't cache this long.
I'm sorry, but I had to modify the generated JS file myself to allow this functionality. As the file is generated and not a part of this repository, I can't make a branch and modify it. The best thing I can do is to add a comment at the top of the file pointing to your licence in this repository.
I'm currently using Muses internally on my machine only, but maybe I'll use it on a public website.

**Comment by fbricker** [comment]
That's ok for you to modify the player if it works for your case. But in order to release/publish this change you should consider that not every browser guarantees a good memory management on endless audio files.

Said so, if you want to go ahead with this change, this are some things you should consider:

1) Metadata display: As the player displays metadata the moment it get's the metadata, pausing the player 15 minutes and then pressing play, will cause metadata to be 15 minutes ahead of what you're actually listening to. If you don't use metadata, there's no issue, but if you do use it, then you should implement some kind of metadata fifo, so you can begin to store metadata the moment the user presses pause and start consuming it again when it presses play in a time-controlled way.

2) Automatic reconnect: If your internet connection gets interrupted / fails while you're in pause mode, Muses will detect this and disconnect your streaming, re-connect it and do play. So a paused player may begin to play again automatically and loose the buffered audio of the moment you pressed play. To make a good pause, you should modify the routines that handles connection interruption, to reconnect on a different audio object where you begin to cache the audio again, so later, when the user clicks play again, you can do play on the original audio object until it's run out of buffer and then you'll need to switch to the new one. Also, if the internet connection fails N times during the pause period, you should generate a fifo of N audio objects to begin consuming one you play the streaming again.

3) Buffering management / release: Muses will automatically disconnect and re-connect to a streaming every a fixed amount of time (60 minutes by default). This is to prevent memory consumption on some browsers. The solution for this may be to limit the pause time or to disable the auto-reconnect feature.

I think if you consider this cases, you'll be good to go.
